server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  mongodb:
    uri: "mongodb+srv://BrandonBaker:Atlas12345@cluster0.dgujh.mongodb.net/"
    database: "Tipster"
